### PR TITLE
FileWriter: resolve cyclic dependency

### LINKED ISSUE #213: cannot import CAF::TextRender or CCM::TextRender
causes failure of aii opennebula tests

new cyclic dependency introduced by #204 
```
[stdweird@spikev ~]$ PERL5LIB=/usr/lib/perl/ perl -e 'use CAF::TextRender'
Undefined subroutine &CAF::Reporter::get_template_instance called at /usr/lib/perl/CAF/Reporter.pm line 70.
Compilation failed in require at /usr/lib/perl/CAF/FileWriter.pm line 30.
BEGIN failed--compilation aborted at /usr/lib/perl/CAF/FileWriter.pm line 30.
Compilation failed in require at /usr/lib/perl/CAF/TextRender.pm line 28.
BEGIN failed--compilation aborted at /usr/lib/perl/CAF/TextRender.pm line 28.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
[stdweird@spikev ~]$ PERL5LIB=/usr/lib/perl/ perl -e 'use CAF::FileWriter;use CAF::TextRender'
```

this is not spotted by the old load or new tqu tests.

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #213

### CODE REVIEW

**Comment by stdweird** [comment]
@ned21 @jrha required hot fix
@jouvin this makes aii fail
