### ISSUE TITLE
cannot import CAF::TextRender or CCM::TextRender

### ISSUE THREAD

**Issue by stdweird** [quattor/CAF#213]
causes failure of aii opennebula tests

new cyclic dependency introduced by #204 
```
[stdweird@spikev ~]$ PERL5LIB=/usr/lib/perl/ perl -e 'use CAF::TextRender'
Undefined subroutine &CAF::Reporter::get_template_instance called at /usr/lib/perl/CAF/Reporter.pm line 70.
Compilation failed in require at /usr/lib/perl/CAF/FileWriter.pm line 30.
BEGIN failed--compilation aborted at /usr/lib/perl/CAF/FileWriter.pm line 30.
Compilation failed in require at /usr/lib/perl/CAF/TextRender.pm line 28.
BEGIN failed--compilation aborted at /usr/lib/perl/CAF/TextRender.pm line 28.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
[stdweird@spikev ~]$ PERL5LIB=/usr/lib/perl/ perl -e 'use CAF::FileWriter;use CAF::TextRender'
```

this is not spotted by the old load or new tqu tests.

**Comment by stdweird** [comment]
this is worse, also CCM::TextRender fails to import on its won
